### ISSUE TITLE
Crypt

### ISSUE THREAD

**Issue by Khizhniak** [bytecode77/pe-union#10]
If I do not know if the .exe that I am gluing is encrypted and if I turn on the cryptor during the gluing, will the files work if they have already been encrypted?

**Comment by bytecode77** [comment]
If you check "encrypt", then the files will be encrypted and work as expected. You can verify this by running the executable in a VM.

**Comment by Khizhniak** [comment]
Thank you!

What the options do in the modification file
1. Compress
2. Crypt (as could i understand this optional will crypt this file with specificity in code generation)
3. Hidden 
?

**Comment by bytecode77** [comment]
Yes, you understood correctly - the encrypted file is stored as a `byte[]` in the generated code and decrypted when the stub is run.

**Comment by Khizhniak** [comment]
Okay, and what about compress and hidden?

**Comment by bytecode77** [comment]
The "Compress"-Flag compresses the `byte[]` prior to encryption. "Hidden" sets the HIDDEN|SYSTEM file attributes when dropping the file.

**Comment by Khizhniak** [comment]
Thank you very much! Your project the best!
