### ISSUE TITLE
RunPE,Invoke error

### ISSUE THREAD

**Issue by protataetuk** [bytecode77/pe-union#17]
Cannot use .NET executable file.exe with RunPE.
And when i use Invoke gives me this error:
.NET Invocation is only supported in a .NET stub.
How can i fix that?

**Comment by bytecode77** [comment]
You should use the .NET stub when invoking .NET executables:
![image](https://user-images.githubusercontent.com/34607975/133978322-cb9910ce-1b30-4819-9475-24350cde05c5.png)

RunPE is for native executables only. You can RunPE native executables from the native **or** the .NET stub.

However, C# executables can only be invoked from a .NET stub using `Invoke`. RunPE simply doesn't do well with C# executables.

**Comment by protataetuk** [comment]
Well i tried the 3 of them and still has the same error

**Comment by bytecode77** [comment]
What error do you get / can you post a screenshot that shows the error? You can black out personal information from the screenshot.

**Comment by protataetuk** [comment]
![image](https://user-images.githubusercontent.com/78657954/134499723-305ab201-c0f7-49d5-9d1a-2439034ec0c9.png)
thats with native 32bit

**Comment by protataetuk** [comment]
![image](https://user-images.githubusercontent.com/78657954/134499959-e8921b14-51f9-4c28-9c12-0c9769d5b7d9.png)
Invoke with native 32bit

**Comment by bytecode77** [comment]
Error message:

> Cannot use .NET executable 'Client.exe' with RunPE. Use a .NET stub with an invoke action instead.

So, `Client.exe` is a program written in C#. Therefore:

- you need to select the **.NET Stub**, not the native stub
- and use **Invoke** instead of RunPE

**Comment by protataetuk** [comment]
Thanks very much!And one more thing.Can you explain me what is the Invoke function doing beacuse im a beginner at programming and can understand what the explanation in the program says.
![image](https://user-images.githubusercontent.com/78657954/134776960-c455bf07-e2bc-4684-ba68-eaffa65275a2.png)

**Comment by bytecode77** [comment]
This method is used for C# binaries instead of process hollowing.

A very short example:

```
byte[] executable = ... // Decrypt in memory, file is not located on disk
Assembly.Load(executable).EntryPoint.Invoke(null, null);
```

**Comment by protataetuk** [comment]
Thanks for your time i understand now!
