### ISSUE TITLE
Question abt editing stub

### ISSUE THREAD

**Issue by erxlol** [bytecode77/pe-union#23]
Hello I am new to coding in general. I am wondering in what way can I edit the stub to make it a different signature so it is FUD again?

**Comment by bytecode77** [comment]
I'm afraid you won't achieve your goal, to make PEunion FUD if you have no prior coding experience. Furthermore, you will need a lot of knowledge in executable structure, AV evasion, etc.

**Comment by erxlol** [comment]
Damn ok.
