### ISSUE TITLE
command line support

### ISSUE THREAD

**Issue by mgeeky** [bytecode77/pe-union#26]
Hello @bytecode77 !

Any plans on adding CLI / command line support for your tool? :)
I would love to add support for it in my [ProtectMyTooling](https://github.com/mgeeky/ProtectMyTooling) but currently cannot do so due to inability to invoke it from CLI.

Or is it `pebuild.exe` I should use to invoke it instead? I'm unsure.

Happy Christmas,
Mariusz.

**Comment by bytecode77** [comment]
Yes, `peubuild.exe` is the command line compiler, and it's actually invoked by the PEunion GUI using this simple command line:
```
peubuild.exe "My Project.peu" "Output File.exe"
```

*You'll get a help text, when you invoke it without any command line.*

Only thing is that you must create a `.peu` file that specifies the input files and how to handle them, which should hopefully not be an issue in your integration. The `.peu` file is actually an INI file.

Unfortunately, I didn't get around to document the structure of the INI file, but you can tell by saving a project and looking at the generated INI file.

**Comment by mgeeky** [comment]
Got it! Works like a charm :) Thanks for the quick response!
