### ISSUE TITLE
getting error like something

### ISSUE THREAD

**Issue by atulkunal999** [bytecode77/pe-union#5]
![Screenshot (16)](https://user-images.githubusercontent.com/44960066/73131378-0b468400-4030-11ea-9884-be35b327b0d0.png)

**Comment by bytecode77** [comment]
This looks like a typical AV issue, where anti virus software deleted temporary files during the build process. Can you check by de-activating your AV / Windows Defender?

**Comment by Tylerkiller2345** [comment]
I have the same problem and it cuts off the first part of my username on windows

**Comment by kev6070** [comment]
Hi the Binder works perfectly when antivirus is off my binded file launches perfectly. But when I turn it on it does not run

**Comment by ZephyrGT** [comment]
Run as administrator can be %Temp% locked

**Comment by dimeks** [comment]
not fud?
